### ISSUE TITLE
VSCode: Cannot find module '@monorepo/utils'

### ISSUE THREAD

**Issue by khokm** [Tonel/typescript-monorepo#1]
When opening file `ui/src/index.ts` in VSCode, you get an error message.
This happens because in `utils/package.json` the 'main' field refers to `build/index.js`, which didn't exist at this point.

The monorepo should work without calling 'npm build' every time after changing code of any of packages.

**Comment by Tonel** [comment]
@khokm 
Check out the tutorial supporting this repository: https://earthly.dev/blog/setup-typescript-monorepo/
